name: EKS Infrastructure + K8s Services

on:
  workflow_dispatch:
    inputs:
      infra_path:
        description: "Path to the Terraform infrastructure directory"
        required: true
        type: choice
        options:
          - EKS/core-cluster
          - EKS/k8s-services
          - 3-tier-app/infra

      apply_destroy:
        description: "Apply or destroy the infrastructure"
        required: true
        type: choice
        options:
          - apply
          - destroy

      terraform_version:
        description: "Terraform version"
        required: false
        type: string
        default: "1.12.1"

jobs:
  infra_apply_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Initialize Terraform
        working-directory: ${{ inputs.infra_path }}
        run: terraform init

      - name: Apply or Destroy Terraform
        working-directory: ${{ inputs.infra_path }}
        run: terraform ${{ inputs.apply_destroy }} --auto-approve